### ISSUE TITLE
What are the possible reasons of tokio-postgres being slower than postgres?

### ISSUE THREAD

**Issue by pwtail** [bikeshedder/rust-postgres-benchmark#1]
I mean, it always seems that the postgres server does most of the work, and the cliens are mostly waiting for data. Then the async model should be a big win. Isn't that so?

**Comment by bikeshedder** [comment]
This benchmark is flawed in some ways. It never performs a `fork`/`spawn` operation and is therefore single threaded. The `postgres` crate is based on `tokio-postgres` so the differences are mostly related to the runtime configuration than any real performance differences.

I've just added the latest `tokio-postgres` and `postgres` versions to this repository and rerun the benchmarks: https://github.com/bikeshedder/rust-postgres-benchmark/blob/master/README.md

As you can see `postgres-0.19.4` and `tokio-postgres-0.7.7_current_thread` perform identical. The outlier is `tokio-postgres-0.7.7` which uses the (default) multi threaded runtime.

If this benchmark was using multiple threads and/or tokio workers the results would probably look different.

Real threads aren't that terrible performance wise. Async code comes with its own huge mountain of problems and threads are rather cheap and perform good enough for most applications.

**Comment by pwtail** [comment]
Thank you for detailed comment, really appreciated that. You may close this if you want
